# -*- coding: utf-8 -*-
"""Intelligence_Sicurezza_MI_MB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fap2XoXzgV2Mk1x47_C5DzMpDqhbXSPu
"""

# Installazione librerie necessarie


from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import folium
from fpdf import FPDF
from datetime import datetime
import time

def analizzatore_intelligence(indirizzo):
    # Usiamo un identificativo unico per evitare blocchi 403
    random_id = f"OSINT_Analyst_MI_MB_{int(time.time())}"
    geolocator = Nominatim(user_agent=random_id)

    try:
        # Ricerca dell'indirizzo con timeout di sicurezza
        location = geolocator.geocode(indirizzo, addressdetails=True, timeout=10)

        if not location:
            return "Indirizzo non trovato"

        info = location.raw['address']
        # Estrazione flessibile del comune
        comune = info.get('city') or info.get('town') or info.get('village') or info.get('suburb')
        provincia = info.get('county', '')

        # Filtro geografico MI e MB
        aree_abilitate = ["Milano", "Monza e della Brianza", "Monza e Brianza"]
        if not any(area in provincia for area in aree_abilitate):
            return f"Fuori zona (Rilevato: {provincia})"

        return {
            "indirizzo": indirizzo,
            "comune": comune,
            "provincia": provincia,
            "lat": location.latitude,
            "lon": location.longitude,
            "data": datetime.now().strftime("%d/%m/%Y %H:%M")
        }
    except Exception as e:
        return f"Errore tecnico: {e}"

def genera_pdf_professionale(dati):
    pdf = FPDF()
    pdf.add_page()

    # Intestazione Intelligence
    pdf.set_font("Arial", "B", 18)
    pdf.set_text_color(20, 40, 80) # Blu scuro istituzionale
    pdf.cell(0, 15, "DOSSIER SICUREZZA TERRITORIALE", ln=True, align="C")

    pdf.set_font("Arial", "B", 10)
    pdf.set_text_color(100)
    pdf.cell(0, 5, f"RIF: {dati['data']} | AMBITO: {dati['provincia'].upper()}", ln=True, align="C")
    pdf.ln(10)

    # Blocco Target
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(0)
    pdf.cell(0, 10, f" 1. LOCALIZZAZIONE TARGET", ln=True, fill=True)
    pdf.set_font("Arial", "", 11)
    pdf.ln(3)
    testo_loc = (f"Indirizzo: {dati['indirizzo']}\n"
                 f"Comune: {dati['comune']}\n"
                 f"Provincia: {dati['provincia']}\n"
                 f"Coordinate: {dati['lat']}, {dati['lon']}")
    pdf.multi_cell(0, 8, testo_loc)

    # Blocco Analisi Istituzionale
    pdf.ln(5)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, " 2. QUADRO AUTORITÀ COMPETENTI", ln=True, fill=True)
    pdf.set_font("Arial", "", 11)
    prefettura = "Milano (C.so Monforte/Via Vivaio)" if "Milano" in dati['provincia'] else "Monza (Via della Signora)"
    testo_enti = (f"- Prefettura di riferimento: {prefettura}\n"
                  f"- Area Questura: Provinciale {dati['provincia']}\n"
                  f"- Vigilanza Urbana: Comando Polizia Locale di {dati['comune']}")
    pdf.multi_cell(0, 8, testo_enti)

    # Blocco Valutazione Argomentata
    pdf.ln(5)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, " 3. ANALISI PRELIMINARE OSINT", ln=True, fill=True)
    pdf.set_font("Arial", "I", 11)
    valutazione = (f"L'area del comune di {dati['comune']} è soggetta alle direttive del Comitato Provinciale "
                   "per l'Ordine e la Sicurezza Pubblica. Si segnala il monitoraggio attivo tramite sistemi "
                   "di videosorveglianza integrata e protocolli di sicurezza partecipata.")
    pdf.multi_cell(0, 8, valutazione)

    nome_file = f"Report_Intelligence_{dati['comune']}.pdf"
    pdf.output(nome_file)
    return nome_file

print("✅ Sistema di Intelligence configurato correttamente.")

# --- CONFIGURAZIONE TARGET ---
indirizzo_target = "Piazza del Duomo, Milano" # Inserisci l'indirizzo desiderato qui
# -----------------------------

risultato = analizzatore_intelligence(indirizzo_target)

if isinstance(risultato, dict):
    # 1. Generazione Mappa
    print(f"🌍 Generazione mappa tattica per {risultato['comune']}...")
    mappa = folium.Map(location=[risultato['lat'], risultato['lon']], zoom_start=16, tiles="OpenStreetMap")
    folium.Marker(
        [risultato['lat'], risultato['lon']],
        popup=indirizzo_target,
        icon=folium.Icon(color='red', icon='info-sign')
    ).add_to(mappa)

    # 2. Creazione PDF
    file_pdf = genera_pdf_professionale(risultato)
    print(f"📄 Report Intelligence creato con successo: {file_pdf}")
    print("📂 Puoi scaricarlo cliccando sull'icona della cartella a sinistra.")

    display(mappa)
else:
    print(f"⚠️ Attenzione: {risultato}")
